FROM maven:3.5.0-jdk-8-alpine AS build
ENV BUILD_ENV_PROFILE=prod
ADD . /tmp/

RUN echo $' \n\
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 \n\
                      https://maven.apache.org/xsd/settings-1.0.0.xsd"> \n\
    <localRepository>/data/wieof/cache/mvn</localRepository> \n\
    <profiles> \n\
        <profile> \n\
            <id>nexus</id> \n\
            <repositories> \n\
                    <repository> \n\
                                    <id>central</id> \n\
                                    <name>Nexus</name> \n\
                                    <url>http://local-maven.wieof.com/repository/maven-public/</url> \n\
                                    <releases><enabled>true</enabled></releases> \n\
                                    <snapshots><enabled>true</enabled></snapshots> \n\
                                </repository> \n\
                    <repository>\n\
                        <id>nexus-tencentyun</id>\n\
                        <url>http://maven.aliyun.com/nexus/content/groups/public/</url> \n\
                        <releases>\n\
                            <enabled>true</enabled>\n\
                        </releases>\n\
                        <snapshots>\n\
                            <enabled>false</enabled>\n\
                        </snapshots>\n\
                    </repository>\n\
            </repositories> \n\
            <pluginRepositories> \n\
                <pluginRepository> \n\
                                <id>central</id> \n\
                                <name>Nexus</name> \n\
                                <url>http://local-maven.wieof.com/repository/maven-public/</url> \n\
                                <releases><enabled>true</enabled></releases> \n\
                                <snapshots><enabled>true</enabled></snapshots> \n\
                            </pluginRepository> \n\
                <pluginRepository> \n\
                    <id>tencent-central</id> \n\
                    <name>Nexus-tencent</name> \n\
                    <url>http://maven.aliyun.com/nexus/content/groups/public/</url> \n\
                    <releases><enabled>true</enabled></releases> \n\
                    <snapshots><enabled>true</enabled></snapshots> \n\
                </pluginRepository> \n\
            </pluginRepositories> \n\
        </profile> \n\
    </profiles> \n\
    <activeProfiles> \n\
        <activeProfile>nexus</activeProfile> \n\
    </activeProfiles> \n\
</settings> '> /usr/share/maven/ref/settings-docker.xml && \
cd /tmp/ && \
mvn clean package -DskipTests=true  -P${BUILD_ENV_PROFILE} -gs /usr/share/maven/ref/settings-docker.xml

FROM tomcat:9.0.1-jre8-alpine AS runtime
ENV JAVA_OPTS="${JAVA_OPTS} -Duser.timezone=GMT+08 -Dfile.encoding=UTF-8 -Xmx2G -Xms2G -Xmn1G -Xss256k -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dlog4j2.formatMsgNoLookups=true"
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build /tmp/target/ROOT.war /usr/local/tomcat/webapps/
EXPOSE 8080
RUN apk add --update ttf-dejavu fontconfig

CMD ["catalina.sh", "run"]