apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-metrics-dpt
  namespace: metrics
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-metrics
      cluster: aliyun-test
      from: deploy
      ns: metrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-metrics
        cluster: aliyun-test
        from: deploy
        ns: metrics
    spec:
      containers:
      - env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.cn-beijing.aliyuncs.com/xxxxx/node-metrics:1666149174
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8089
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: node-metrics
        ports:
        - containerPort: 8089
          name: tcp8089
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8089
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 256M
          requests:
            cpu: 100m
            memory: 256M
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-metrics
    cluster: aliyun-test
    from: deploy
    ns: metrics
  name: node-metrics-svc
  namespace: metrics
spec:
  ports:
  - name: tcp8089
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: node-metrics
    cluster: aliyun-test
    from: deploy
    ns: metrics
  sessionAffinity: None
  type: ClusterIP
--- 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-metrics-svc-monitor
  namespace: metrics
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    interval: 30s
    path: /metrics
    port: tcp8089
    scheme: http
  jobLabel: node-metrics-dpt
  namespaceSelector:
    matchNames:
    - metrics
  selector:
    matchLabels:
      app: node-metrics
      cluster: aliyun-test
      from: deploy
      ns: metrics